### ISSUE TITLE
docs.rs: view source cuts off left side

### ISSUE THREAD

**Issue by xobs** [RustCrypto/hashes#106] opened 2020-03-16 00:57 UTC
When viewing source on docs.rs, the entire left side of the code listing is not visible.  For example, viewing https://docs.rs/sha3/0.8.2/src/sha3/lib.rs.html#1-96:

![image](https://user-images.githubusercontent.com/238325/76714760-ffd82500-6763-11ea-80c2-34fb0ed14d2c.png)

These links are generated by clicking on `[src]` anywhere in the documentation.

**Comment by tarcieri** [comment] 2020-03-16 14:04
Any idea why this might be the case?

**Comment by xobs** [comment] 2020-03-16 14:54
I'm not sure.  That class is "sidebar", which has a background of #fff, but that is the same as other packages on docs.rs.

**Comment by newpavlov** [comment] 2020-05-26 04:42
The problem is in `z-index: 1;` property. Surprisingly, it looks like docs.rs uses different CSS files for different crates, for example it's `rustdoc-20190417-1.36.0-nightly-3c3d3c177.css` and `rustdoc-20200522-1.45.0-nightly-215f2d329.css` for `sha3 v0.8.2` and `sha2 v0.8.2` pages respectively. So if I am not mistaken this issue will be "fixed" on a next crate upload, thus I think we can close it.

Additionally you can create an issue in the docs.rs [repository](https://github.com/rust-lang/docs.rs/), so they could regenerate pages with a fixed CSS file.

**Closed as completed** 2020-05-28 18:53 UTC
