### ISSUE TITLE
Blake2 method `KeyInit::new` is incorrect and not tested

### ISSUE THREAD

**Issue by vlad9486** [RustCrypto/hashes#433] opened 2022-11-11 08:13 UTC
Now it is crashing:

```
#[cfg(test)]
#[test]
fn blake2b_trivial() {
    use blake2::{Blake2bMac512, digest::KeyInit};

    <Blake2bMac512 as KeyInit>::new(&Default::default());
}
```

Because of this
https://github.com/RustCrypto/hashes/blob/af0567f2605901bf6b4811775427c8f1dd7e350d/blake2/src/macros.rs#L328

This line is passing key as salt, but it should not.

**Comment by vlad9486** [comment] 2022-11-11 08:15
#432

**Comment by newpavlov** [comment] 2022-11-11 10:01
The issue is fixed in v0.10.5. I will close this issue after tests for `KeyInit::new` will be added.

**Closed as completed** 2022-11-14 10:40 UTC
